spring.application.name=accountService
server.port=9096

#spring.datasource.url=jdbc:mysql://localhost:3306/hcl
#spring.datasource.username=root
#spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.eiijvpnbkemvfbppfpmr
spring.datasource.password=zqGF2uM7X9JAYl1M
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
